### PR TITLE
Various issue fixes

### LINKED ISSUE #208: cat_fb_crouch
Have bot crouch when target is crouching. Maybe add a check to only do so when they're crouching for more than half a second, that way you don't crouch with someone that has a crouch/jump script.

Also, have bot crouch when target is heavy spinning up. Walks just as fast if not faster than a heavy attacking, so it'll help keep the bot a little more hidden/smaller target to hit.

### LINKED ISSUE #536: Make settings auto save.
Sometimes the game crashes and if you made many change in cheat then you will have to redo all change. But only make it save when you exit the cheat menu, because some features crash your game even in main menu.

### LINKED ISSUE #802: Sniper navbot switches between primary/secondary "randomly"
Bot's unable to properly attack anyone within ~200 due to switching delays. Players are likely to run around and flank the sniper bot, resulting in the bot constantly switching back and forth between the two weapons - occasionally getting a single bullet out with the secondary every so often.

Suggesting to just double this range, or add a small delay before switching back to primary

### PR DESCRIPTION
**Pull request by TotallyNotElite**
Fixes #208 
Fixes #802 
Fixes #536 

Testing:
- [x] Autosaves
- [x]  Logging
- [x] Followbot autocrouch
- [x] Getbestslot

### CODE REVIEW

File: src/settings/SettingsIO.cpp [hunk 1]
```diff
@@ -14,31 +14,38 @@ settings::SettingsWriter::SettingsWriter(settings::Manager &manager) : manager(m
...
 }
 
-bool settings::SettingsWriter::saveTo(std::string path)
+bool settings::SettingsWriter::saveTo(std::string path, bool autosave)
 {
-    logging::Info("cat_save: started");
+    if (autosave)
+        logging::File("cat_save: Saving to %s", path.c_str());
+    else
+    {
```
Comment (BenCat07) [inline src/settings/SettingsIO.cpp]: unneeded { that trigger me

Comment (BenCat07) [reply src/settings/SettingsIO.cpp]: Not important though

File: src/hacks/Misc.cpp [hunk 2]
```diff
@@ -39,12 +41,19 @@ static settings::Boolean no_homo{ "misc.no-homo", "true" };
...
 
-static void tryPatchLocalPlayerShouldDraw(settings::VariableBase<bool> &, bool after)
+#if !ENFORCE_STREAM_SAFETY && ENABLE_VISUALS
+static void tryPatchLocalPlayerShouldDraw(bool after)
 {
     static BytePatch patch_shoulddraw{ gSignatures.GetClientSignature, "80 BB ? ? ? ? ? 75 DE", 0xD, { 0xE0 } };
     after ? patch_shoulddraw.Patch() : patch_shoulddraw.Shutdown();
 }
 
+static void tryPatchLocalPlayerShouldDraw_callback(settings::VariableBase<bool> &, bool after)
```
Comment (robootgit) [inline src/hacks/Misc.cpp]: Why create a function that only exists to call another function with the same visibility?

File: src/core/logging.cpp [hunk 3]
```diff
@@ -62,13 +48,51 @@ void logging::Info(const char *fmt, ...)
...
+void logging::Info(const char *fmt, ...)
+{
+#if ENABLE_LOGGING
+    if (shut_down)
+        return;
+    // Argument list
+    va_list list;
+    va_start(list, fmt);
+    // Allocate buffer
+    auto result = std::make_unique<char[]>(512);
```
Comment (robootgit) [inline src/core/logging.cpp]: Heap allocation here is unnecessary.

File: src/core/logging.cpp [hunk 4]
```diff
@@ -62,13 +48,51 @@ void logging::Info(const char *fmt, ...)
...
+void logging::File(const char *fmt, ...)
+{
+#if ENABLE_LOGGING
+    if (shut_down)
+        return;
+    // Argument list
+    va_list list;
+    va_start(list, fmt);
+    // Allocate buffer
+    auto result = std::make_unique<char[]>(512);
```
Comment (robootgit) [inline src/core/logging.cpp]: Heap allocation here is unnecessary.

File: src/hacks/Misc.cpp (hunk 2 above)
Comment (TotallyNotElite) [reply src/hacks/Misc.cpp]: The function is being called from 2 locations: on init, on variable change callback

Comment (BenCat07) [reply src/hacks/Misc.cpp]: The callback has to work with a function with specific Arguments. i Either duplicated the code in the top function, made a new callback function to call the one, or use a lambda instead of a new functioncto call that function.

File: src/hacks/NavBot.cpp [hunk 5]
```diff
@@ -605,10 +605,9 @@ enum slots
     secondary = 2,
     melee     = 3
 };
-static int GetBestSlot()
+static slots GetBestSlot(slots active_slot)
```
[the remark this answers is not in the document]
Comment (BenCat07) [reply src/hacks/NavBot.cpp]: getBestSlot

**Comment by TotallyNotElite** [comment]
@BenCat07 @robootgit can I get an updated review? Logging is not tested yet and neither is @hwgs's aimbot.cpp change. @BenCat07 can I get approval for renaming latest to stable?

**Comment by BenCat07** [comment]
i would make a new tag called stable and keep latest for compability reasons, but make all new cathook versions switch to stable

File: src/hacks/Aimbot.cpp [hunk 6]
```diff
@@ -1097,7 +1097,12 @@ int BestHitbox(CachedEntity *target)
             {
 
                 float cdmg = CE_FLOAT(LOCAL_W, netvar.flChargedDamage);
-                float bdmg = CarryingHeatmaker() ? 40 : 50;
+                float bdmg = 50;
+                if (CarryingHeatmaker())
+                {
+                    bdmg = (bdmg * .80) - 1;
```
Comment (BenCat07) [inline src/hacks/Aimbot.cpp]: am i seeing this correctly? bodyshot damage does not scale with charge? you may want to change it does.

Comment (BenCat07) [reply src/hacks/Aimbot.cpp]: i know this is not your fault, but it should still be fixed

File: src/hacks/NavBot.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (BenCat07) [reply src/hacks/NavBot.cpp]: fixed

File: src/hacks/Misc.cpp (hunk 2 above)
Comment (BenCat07) [reply src/hacks/Misc.cpp]: fixed

File: src/core/logging.cpp (hunk 4 above)
Comment (BenCat07) [reply src/core/logging.cpp]: fixed

File: src/core/logging.cpp (hunk 3 above)
Comment (BenCat07) [reply src/core/logging.cpp]: fixed

File: src/hacks/Aimbot.cpp (hunk 6 above)
Comment (TotallyNotElite) [reply src/hacks/Aimbot.cpp]: What do you mean?

Comment (TotallyNotElite) [reply src/hacks/Aimbot.cpp]: bdmg refers to the damage dealt while not being zoomed in.

**Comment by TotallyNotElite** [comment]
> i would make a new tag called stable and keep latest for compability reasons, but make all new cathook versions switch to stable

That's the plan. Latest will only get the next update and then all future updates will be distributed via the stable tag. Sounds good?

File: src/hacks/Aimbot.cpp (hunk 6 above)
Comment (BenCat07) [reply src/hacks/Aimbot.cpp]: Ah my bad

**Comment by BenCat07** [comment]
> > i would make a new tag called stable and keep latest for compability reasons, but make all new cathook versions switch to stable
> 
> That's the plan. Latest will only get the next update and then all future updates will be distributed via the stable tag. Sounds good?

Sounds good
